openapi: 3.0.1
info:
    title: Taste Food Management API
    contact:
        name: Grupo 13
    version: 1.0.0
servers:
    - url: /
tags:
    - name: customer
      description: API de clientes
paths:
    /auth/signUp:
        post:
            tags:
                - auth
            summary: Cadastrar cliente
            operationId: CustomerSignUp
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/SignUpRequest"
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/SignUpResponse"
                "400":
                    description: Bad Request
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/SignUpResponse"
                "500":
                    description: Internal Server Error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/SignUpResponse"
            x-amazon-apigateway-integration:
                uri: ${lambda_auth_sign_up_arn}
                credentials: ${api_gateway_role}
                passthroughBehavior: when_no_match
                httpMethod: POST
                type: aws_proxy
    /auth/signIn:
        post:
            tags:
                - auth
            summary: Login do Cliente
            operationId: CustomerSignIn
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/SignInRequest"
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/SignInTokenResponse"
                "400":
                    description: Bad Request
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/SignInErrorResponse"
                "500":
                    description: Internal Server Error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/SignInErrorResponse"
            x-amazon-apigateway-integration:
                uri: ${lambda_auth_sign_in_arn}
                credentials: ${api_gateway_role}
                passthroughBehavior: when_no_match
                httpMethod: POST
                type: aws_proxy
